import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#102000",
        "on-surface": "#0b1c30",
        "on-primary-fixed": "#001947",
        "secondary-container": "#acf847",
        "on-background": "#0b1c30",
        "inverse-surface": "#213145",
        "error-container": "#ffdad6",
        surface: "#f8f9ff",
        "primary-fixed-dim": "#b1c5ff",
        "on-secondary-container": "#457000",
        "on-tertiary-fixed-variant": "#3a485b",
        primary: "#0048af",
        "surface-container": "#e5eeff",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-bright": "#f8f9ff",
        "tertiary-container": "#5a687c",
        "inverse-on-surface": "#eaf1ff",
        "tertiary-fixed-dim": "#b9c7df",
        secondary: "#416900",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#0d1c2e",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#2b61cc",
        "primary-fixed": "#dae2ff",
        "surface-dim": "#cbdbf5",
        background: "#f8f9ff",
        "surface-container-high": "#dce9ff",
        "on-error": "#ffffff",
        "inverse-primary": "#b1c5ff",
        "surface-container-low": "#eff4ff",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#d9e7ff",
        "secondary-fixed-dim": "#91db2a",
        "on-primary-container": "#dee5ff",
        outline: "#737784",
        "on-primary-fixed-variant": "#00419f",
        "surface-variant": "#d3e4fe",
        "on-secondary-fixed-variant": "#304f00",
        error: "#ba1a1a",
        "tertiary-fixed": "#d5e3fc",
        "surface-container-highest": "#d3e4fe",
        tertiary: "#425064",
        "surface-tint": "#1e58c3",
        "on-surface-variant": "#434653",
        "outline-variant": "#c3c6d5",
        "secondary-fixed": "#acf847",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      spacing: {
        "section-gap": "8rem",
        gutter: "1.5rem",
        "bento-gap": "1.5rem",
        "margin-mobile": "1rem",
        "margin-desktop": "4rem",
      },
      fontFamily: {
        "headline-xl": ["var(--font-outfit)", "sans-serif"],
        "body-md": ["var(--font-lato)", "sans-serif"],
        "headline-lg": ["var(--font-outfit)", "sans-serif"],
        "headline-md": ["var(--font-outfit)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-outfit)", "sans-serif"],
        "body-lg": ["var(--font-lato)", "sans-serif"],
        "label-sm": ["var(--font-lato)", "sans-serif"],
      },
      fontSize: {
        "headline-xl": [
          "64px",
          {
            lineHeight: "1.1",
            letterSpacing: "-0.03em",
            fontWeight: "800",
          },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": [
          "40px",
          {
            lineHeight: "1.2",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "headline-md": [
          "28px",
          {
            lineHeight: "1.3",
            letterSpacing: "-0.01em",
            fontWeight: "700",
          },
        ],
        "headline-lg-mobile": [
          "32px",
          {
            lineHeight: "1.2",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": [
          "14px",
          { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};
export default config;
